main = "./src/index.ts"
name = "levo-cf-worker"
compatibility_date = "2022-07-26"

[vars]
LEVO_ENV = "staging"
LEVO_SATELLITE_URL = "https://collector.levo.ai"
LEVO_ADDITIONAL_HEADERS = ""

# The following variable is recommended to be added as a secret:
#
# LEVO_ORG_ID
#
# Run `echo <VALUE> | wrangler secret put LEVO_ORG_ID` to add it.
